SELECT COUNT(*)
FROM ORDERS
WHERE O_ORDERKEY IN (
	SELECT L_ORDERKEY
	FROM LINEITEM
	WHERE L_SUPPKEY IN (
		SELECT S_SUPPKEY
		FROM SUPPLIER
		WHERE S_ACCTBAL > 0	
	)
) AND O_CUSTKEY IN ( 
	SELECT C_CUSTKEY
	FROM CUSTOMER
	WHERE C_ACCTBAL < 0	
	
)